id: PE50AC665
initial_creation_type: input
source_metadata:
  title: Palyul Choktrul Series
  language: bo
  description: 'Texts by and about the Nyingma lama Palyul Choktrul Jampal Gyepe Dorje
    (dpal yul mchog sprul ''jam dpal dgyes pa''i rdo rje, 1894–1958/9), who was renowned
    for his strict monastic discipline and statuesque appearance:'
  volume:
    96ef1a792f1a4d168b26b82347024b91:
      title: Advice for Orgyen Rigdzin
      parent: Advice
created_at: '2022-03-01T01:10:21.067157'
last_modified_at: '2022-03-01T01:10:21.067161'
statistics:
  total_words: 130
  total_non_words: 9
quality:
  non_words_ratio: 0.07
